################################################################################
#                        Open API specification version                        #
################################################################################
swagger: '2.0'

################################################################################
#                              Document Information                            #
################################################################################
info:
  $ref: './info/index.yaml'

################################################################################
#                               External Documents                             #
################################################################################
externalDocs: 
  $ref: './externalDocs/index.yaml'

host: 127.0.0.1:8081
basePath: /exampleAPI/location/v1/
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json

################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  $ref: './parameters/index.yaml'

################################################################################
#                                   paths                                      #
################################################################################
paths:
  $ref: './paths/index.yaml'

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  $ref: './definitions/index.yaml'
  
################################################################################
# SEEMINGLY NOT ALLOWED in Swagger/OpenAPI 2.0                                 #
#                                                                              #
#                                 Examples                                     #
################################################################################
#examples:
#  $ref: './examples/index.yaml'